version: '3.4'
services:
  proxy:
    build: ./proxy
    container_name: proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/nginx.conf
      - type: bind
        source: ./proxy/certs
        target: /etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro

  hoge:
    build: ./php-common
    container_name: php-hoge
    working_dir: /var/www/html/hoge
    environment:
      - VIRTUAL_HOST=hoge.hoge.com
    volumes:
      - type: bind
        source: ./data/hoge
        target: /var/www/html/hoge
      - type: bind
        source: ./php-common/hoge.conf
        target: /etc/apache2/apache2.conf
      - type: bind
        source: ./php-common/php.ini
        target: /usr/local/etc/php/php.ini

  foo:
    build: ./php-common
    container_name: php-foo
    working_dir: /var/www/html/foo
    environment:
      - VIRTUAL_HOST=foo.foo.com
    volumes:
      - type: bind
        source: ./data/foo
        target: /var/www/html/foo
      - type: bind
        source: ./php-common/foo.conf
        target: /etc/apache2/apache2.conf
      - type: bind
        source: ./php-common/php.ini
        target: /usr/local/etc/php/php.ini

  hoge_composer:
    build: ./composer
    container_name: hoge_composer
    working_dir: /data/hoge
    restart: 'no'
    volumes:
      - type: bind
        source: ./data/hoge
        target: /data/hoge

  foo_composer:
    build: ./composer
    container_name: foo_composer
    working_dir: /data/foo
    restart: 'no'
    volumes:
      - type: bind
        source: ./data/foo
        target: /data/foo

  hoge_yarn:
    build: ./yarn
    container_name: hoge_yarn
    working_dir: /data/hoge
    restart: 'no'
    volumes:
      - type: bind
        source: ./data/hoge
        target: /data/hoge

  foo_yarn:
    build: ./yarn
    container_name: foo_yarn
    working_dir: /data/foo
    restart: 'no'
    volumes:
      - type: bind
        source: ./data/foo
        target: /data/foo

  mysql:
    build: ./mysql
    container_name: mysql
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=root"
      - "MYSQL_ROOT_PASSWORD=root"
    ports:
      - "3306:3306"

volumes:
  dbdata:
